
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  json-handler:
    build:
      context: .
    container_name: json_handler_container
    volumes:
      - .:/app
    command: sh -c "python json_reassembler.py && python data_handler.py"

  flask-app:
    build:
      context: .
    container_name: flask_app_container
    depends_on:
      - mongodb
      - json-handler
    volumes:
      - .:/app
    ports:
      - "88:5000"
    command: sh -c "python reassembler.py && python app.py"

volumes:
  mongo_data:
