version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Maps port 3000 on your host to port 80 in the container
    environment:
      - NODE_ENV=production
